sudo: required
services:
  - docker

before_install:
  - docker build -t arushsoel/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true arushsoel/react-test npm test -- --coverage

after_success:
  - docker build -t arushsoel/multi-client ./client
  - docker build -t arushsoel/multi-nginx ./nginx
  - docker build -t arushsoel/multi-server ./server
  - docker build -t arushsoel/multi-worker ./worker

# login to Docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

# push images to DockerHub
  - docker push arushsoel/multi-client
  - docker push arushsoel/multi-nginx
  - docker push arushsoel/multi-server
  - docker push arushsoel/multi-worker

deploy:
  provider: elasticbeanstalk
  region: us-east-2
  app: multi-docker
  env: MultiDocker-env
  bucket_name: elasticbeanstalk-us-east-2-792765150061
  bucket_path: docker-multi
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: $AWS_SECRET_KEY

